name: Platiagro deploy

on:
  push:
    branches: [feature/deploy-on-cpqd]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Install VPNC
        run: |
          sudo apt-get install vpnc
      - name: Create VPN Configuration File
        run: |
          sudo bash -c 'cat <<EOF > /etc/vpnc/vpnc.conf
          IPSec gateway ${{ secrets.VPN_GATEWAY }}
          IPSec ID ${{ secrets.VPN_IPSEC_ID }}
          IPSec secret ${{ secrets.VPN_IPSEC_SECRET }}
          Xauth username ${{ secrets.VPN_USERNAME }}
          Xauth password ${{ secrets.VPN_PASSWORD }}
          EOF'
      - name: Connect to VPN
        run: |
          sudo vpnc vpnc
      - name: Create Platiagro VM
        uses: appleboy/ssh-action@master
        with:
          host: 10.50.11.163
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          command_timeout: 50m
          script: |
            VM_NAME=$(printf 'github-%(%Y-%m-%d-%H:%M:%S)T\n' -1)
            echo ${VM_NAME}
            echo ::set-env name=VM_NAME::${VM_NAME}
      - name: Start Platiagro VM
        uses: appleboy/ssh-action@master
        with:
          host: 10.50.11.163
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            echo ${VM_NAME}
      - name: Disconnect to VPN
        run: |
          sudo vpnc-disconnect
