# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [feature/deploy-on-cpqd]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Install VPNC sshpass
        run: |
          sudo apt-get install vpnc sshpass
      - name: Create VPN Configuration File
        run: |
          sudo bash -c 'cat <<EOF > /etc/vpnc/vpnc.conf
          IPSec gateway ${{secrets.VPN_GATEWAY}}
          IPSec ID ${{secrets.VPN_IPSEC_ID}}
          IPSec secret ${{secrets.VPN_IPSEC_SECRET}}
          Xauth username ${{secrets.VPN_USERNAME}}
          Xauth password ${{secrets.VPN_PASSWORD}}
          EOF'
      - name: Connect to VPN
        run: |
          sudo vpnc vpnc
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: 10.50.11.165
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            ls -a
            cat <<EOF > vpnc.conf
            IPSec gateway ${{secrets.VPN_GATEWAY}}
            IPSec ID ${{secrets.VPN_IPSEC_ID}}
            IPSec secret ${{secrets.VPN_IPSEC_SECRET}}
            Xauth username ${{secrets.VPN_USERNAME}}
            Xauth password ${{secrets.VPN_PASSWORD}}
            EOF
      - name: Disconnect to VPN
        run: |
          sudo vpnc-disconnect
